package com.example.utils

enum class AppLanguage {
    EN, ID
}

object LanguageManager {
    private val translations = mapOf(
        AppLanguage.EN to mapOf(
            "app_title" to "Upload Toolkit By RyanLee QX",
            "creator_credit" to "Created by @ryanhardlee",
            "tiktok_profile" to "TikTok Profile: ETER-RyanLee QX",
            "version" to "Version v1.0.0",
            "status_label" to "Status",
            "ready" to "Ready",
            "not_ready" to "Not Ready",
            "select_video" to "Select Video",
            "inspect_video" to "Inspect Video",
            "patch_video" to "Patch Video",
            "copy_caption" to "Copy Caption",
            "open_tiktok" to "Open TikTok",
            "fps_magic" to "FPS Magic",
            "upload_checklist" to "Upload Checklist",
            "test_log" to "Test Log",
            "file_name" to "File Name",
            "file_size" to "File Size",
            "duration" to "Duration",
            "resolution" to "Resolution",
            "aspect_ratio" to "Aspect Ratio",
            "fps" to "FPS",
            "video_codec" to "Video Codec",
            "audio_codec" to "Audio Codec",
            "estimated_bitrate" to "Estimated Bitrate",
            "container_format" to "Container Format",
            "readiness_status" to "Readiness Status",
            "patch_mode" to "Patch Mode",
            "advanced" to "Advanced",
            "advanced_desc" to "Advanced is the main recommended mode (Sample-Table method)",
            "classic" to "Classic",
            "classic_desc" to "Classic is fallback (Matrix repair method)",
            "no_patch" to "No Patch",
            "no_patch_desc" to "No Patch exports/copies original file without modifications",
            "patch_completed" to "Patch completed successfully!",
            "export_btn" to "Apply Patch & Export",
            "detected_fps" to "Detected Input FPS",
            "available_modes" to "Available Modes",
            "output_behavior" to "Output Behavior (Timing-based)",
            "fps_warning" to "Render/transcode mode may affect visual quality if introduced later.",
            "caption_title" to "TikTok Caption Tool",
            "caption_text" to "Upload method by @ryanhardlee",
            "copied" to "Copied!",
            "not_copied" to "Copy Caption",
            "checklist_selected" to "Video selected",
            "checklist_inspected" to "Video inspected",
            "checklist_patched" to "Patch completed or skipped intentionally",
            "checklist_caption" to "Caption copied",
            "checklist_tiktok" to "TikTok opened manually",
            "test_log_title" to "Local Quality Logs",
            "log_date" to "Date/Time",
            "log_file" to "Source File",
            "log_patch" to "Patch Mode",
            "log_fps" to "FPS Mode",
            "log_result" to "Export Result",
            "log_notes" to "User Notes",
            "log_quality" to "Upload Quality",
            "add_log" to "Save Log Entry",
            "quality_placeholder" to "Manual upload result rating...",
            "user_notes_placeholder" to "Add notes (render times, quality, tags...)",
            "delete" to "Delete",
            "clear" to "Clear",
            "no_logs_yet" to "No test logs saved yet.",
            "success" to "Success",
            "failed" to "Failed",
            "visit_linktree" to "Visit Linktree",
            "unsupported_video" to "Selected file is not a supported MP4/Video file.",
            "error" to "Error",
            "inspector_desc" to "Analyze your media specs before manual upload to avoid TikTok compression."
        ),
        AppLanguage.ID to mapOf(
            "app_title" to "Upload Toolkit By RyanLee QX",
            "creator_credit" to "Dibuat oleh @ryanhardlee",
            "tiktok_profile" to "Profil TikTok: ETER-RyanLee QX",
            "version" to "Versi v1.0.0",
            "status_label" to "Status",
            "ready" to "Siap",
            "not_ready" to "Belum Siap",
            "select_video" to "Pilih Video",
            "inspect_video" to "Cek Video",
            "patch_video" to "Patch Video",
            "copy_caption" to "Salin Caption",
            "open_tiktok" to "Buka TikTok",
            "fps_magic" to "FPS Magic",
            "upload_checklist" to "Checklist Upload",
            "test_log" to "Log Uji Coba",
            "file_name" to "Nama File",
            "file_size" to "Ukuran File",
            "duration" to "Durasi",
            "resolution" to "Resolusi",
            "aspect_ratio" to "Rasio Aspek",
            "fps" to "FPS",
            "video_codec" to "Codec Video",
            "audio_codec" to "Codec Audio",
            "estimated_bitrate" to "Bitrate Estimasi",
            "container_format" to "Format Kontainer",
            "readiness_status" to "Status Kesiapan",
            "patch_mode" to "Mode Patch",
            "advanced" to "Advanced",
            "advanced_desc" to "Advanced adalah mode rekomendasi utama (Metode Sample-Table)",
            "classic" to "Classic",
            "classic_desc" to "Classic adalah fallback (Metode reparasi Matrix)",
            "no_patch" to "Tanpa Patch",
            "no_patch_desc" to "Tanpa Patch mengekspor file asli tanpa perubahan",
            "patch_completed" to "Patch berhasil diselesaikan!",
            "export_btn" to "Terapkan Patch & Ekspor",
            "detected_fps" to "Deteksi FPS Input",
            "available_modes" to "Mode Tersedia",
            "output_behavior" to "Perilaku Output (Berbasis timing)",
            "fps_warning" to "Mode render/transcode dapat memengaruhi kualitas visual jika ditambahkan nanti.",
            "caption_title" to "Alat Caption TikTok",
            "caption_text" to "Upload method by @ryanhardlee",
            "copied" to "Disalin!",
            "not_copied" to "Salin Caption",
            "checklist_selected" to "Video telah dipilih",
            "checklist_inspected" to "Video telah dicek",
            "checklist_patched" to "Patch selesai atau sengaja dilewati",
            "checklist_caption" to "Caption telah disalin",
            "checklist_tiktok" to "TikTok dibuka secara manual",
            "test_log_title" to "Log Kualitas Lokal",
            "log_date" to "Tanggal/Waktu",
            "log_file" to "File Sumber",
            "log_patch" to "Mode Patch",
            "log_fps" to "Mode FPS",
            "log_result" to "Hasil Ekspor",
            "log_notes" to "Catatan Pengguna",
            "log_quality" to "Kualitas Upload",
            "add_log" to "Simpan Entri Log",
            "quality_placeholder" to "Penilaian hasil upload manual...",
            "user_notes_placeholder" to "Tambah catatan (waktu render, kualitas, tag...)",
            "delete" to "Hapus",
            "clear" to "Bersih",
            "no_logs_yet" to "Belum ada log uji coba yang disimpan.",
            "success" to "Sukses",
            "failed" to "Gagal",
            "visit_linktree" to "Kunjungi Linktree",
            "unsupported_video" to "File terpilih bukan file MP4/Video yang didukung.",
            "error" to "Kesalahan",
            "inspector_desc" to "Analisis spesifikasi media Anda sebelum upload manual untuk menghindari kompresi TikTok."
        )
    )

    fun getString(key: String, lang: AppLanguage): String {
        return translations[lang]?.get(key) ?: translations[AppLanguage.EN]?.get(key) ?: key
    }
}
